ALTER SESSION SET NLS_DATE_FORMAT = 'dd-mm-yyyy';
SET SERVEROUTPUT ON

DECLARE
  queryString VARCHAR2(2048);
BEGIN
  queryString := '' ||
' CREATE TABLE Myszy ( ' ||
  ' nr_myszy NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT my_pk PRIMARY KEY, ' ||
  ' lowca VARCHAR(15) CONSTRAINT my_lo_fk REFERENCES Kocury(pseudo), ' ||
  ' zjadacz VARCHAR(15) CONSTRAINT my_zj_fk REFERENCES Kocury(pseudo), ' ||
  ' waga_myszy NUMBER  CONSTRAINT wm_nn NOT NULL, CONSTRAINT my_wm_ck CHECK(waga_myszy BETWEEN 15 AND 25), ' ||
  ' data_zlowienia DATE CONSTRAINT dz_nn NOT NULL, ' ||
  ' data_wydania DATE ) ' ;
  DBMS_OUTPUT.PUT_LINE(queryString);
  EXECUTE IMMEDIATE queryString;
END;