--Stworzenie tabeli dla ka¿dego kota
DECLARE
  TYPE KocuryT IS TABLE OF Kocury.PSEUDO%TYPE INDEX BY BINARY_INTEGER;
  koty KocuryT;
  i BINARY_INTEGER;
BEGIN
  SELECT pseudo BULK COLLECT INTO koty FROM Kocury;
  FOR i in 1..koty.COUNT
  LOOP
    EXECUTE IMMEDIATE 'CREATE TABLE '||koty(i)||'
(nr_zlowienia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT kot'||koty(i)||' PRIMARY KEY,
    waga_myszy number CONSTRAINT myszyWaga'||koty(i)||' CHECK(waga_myszy BETWEEN 3 and 33),
    data_zlowienia date NOT NULL)';
    COMMIT;
  END LOOP;
END;

rollback;

SELECT COUNT(*) FROM KOCURY;
