INSERT INTO ObjKoty VALUES('JACEK','M','PLACEK','LYSY','2008-12-01',67,NULL);
INSERT INTO ObjKoty VALUES('BARI','M','RURA',(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='MICKA'),'2009-09-01',56,NULL);
INSERT INTO ObjKoty VALUES('MICKA','D','LOLA',(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='TYGRYS'),'2009-10-14',25,47);
INSERT INTO ObjKoty VALUES('LUCEK','M','ZERO',(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='BARI'),'2010-03-01',43,NULL);
INSERT INTO ObjKoty VALUES('SONIA','D','MILUSIA',(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='DAMA'),'2010-11-18',20,35);
INSERT INTO ObjKoty VALUES('LATKA','D','UCHO','RAFA','2011-01-01',40,NULL);
INSERT INTO ObjKoty VALUES('DUDEK','M','MALY','RAFA','2011-05-15',40,NULL);
INSERT INTO ObjKoty VALUES('MRUCZEK','M','TYGRYS','SZEFUNIO','2002-01-01',103,33);
INSERT INTO ObjKoty VALUES('CHYTRY','M','BOLEK','TYGRYS','2002-05-05',50,NULL);
INSERT INTO ObjKoty VALUES('KOREK','M','ZOMBI','TYGRYS','2004-03-16',75,13);
INSERT INTO ObjKoty VALUES('BOLEK','M','LYSY','TYGRYS','2006-08-15',72,21);
INSERT INTO ObjKoty VALUES('ZUZIA','D','SZYBKA','LYSY','2006-07-21',65,NULL);
INSERT INTO ObjKoty VALUES('RUDA','D','MALA','TYGRYS','2006-09-17',22,42);
INSERT INTO ObjKoty VALUES('PUCEK','M','RAFA','TYGRYS','2006-10-15',65,NULL);
INSERT INTO ObjKoty VALUES('PUNIA','D','KURKA','ZOMBI','2008-01-01',61,NULL);
INSERT INTO ObjKoty VALUES('BELA','D','LASKA','LYSY','2008-02-01',24,28);
INSERT INTO ObjKoty VALUES('KSAWERY','M','MAN','RAFA','2008-07-12',51,NULL);
INSERT INTO ObjKoty VALUES('MELA','D','DAMA','RAFA','2008-11-01',51,NULL);
INSERT INTO ObjKoty VALUES('TYGRYS','D','DAMA',NULL,'2008-11-01',51,NULL);

INSERT INTO ObjPlebs VALUES(5,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='PUNIA'));
INSERT INTO ObjPlebs VALUES(1,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='ZUZIA'));
INSERT INTO ObjPlebs VALUES(2,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='MELA'));
INSERT INTO ObjPlebs VALUES(3,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='KOREK'));
INSERT INTO ObjPlebs VALUES(4,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='KSAWERY'));

INSERT INTO ObjElita VALUES(1,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='CHYTRY'),(SELECT REF(sluga) FROM ObjPlebs sluga WHERE sluga.nr_plebsu=1));
INSERT INTO ObjElita VALUES(2,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='MRUCZEK'),(SELECT REF(sluga) FROM ObjPlebs sluga WHERE sluga.nr_plebsu=2));
INSERT INTO ObjElita VALUES(3,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='RUDA'), (SELECT REF(sluga) FROM ObjPlebs sluga WHERE sluga.nr_plebsu=3));
INSERT INTO ObjElita VALUES(4,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='SONIA'),(SELECT REF(sluga) FROM ObjPlebs sluga WHERE sluga.nr_plebsu=4) );
INSERT INTO ObjElita VALUES(5,(SELECT REF(kot) FROM ObjKoty kot WHERE kot.imie='SONIA'),(SELECT REF(sluga) FROM ObjPlebs sluga WHERE sluga.nr_plebsu=5));

INSERT INTO ObjKonta VALUES(1,(SELECT REF(wlasciciel) FROM ObjElita wlasciciel WHERE wlasciciel.nr_czlonka_elity=1),'2017-01-01',NULL);
INSERT INTO ObjKonta VALUES(2,(SELECT REF(wlasciciel) FROM ObjElita wlasciciel WHERE wlasciciel.nr_czlonka_elity=2),'2017-01-05','2017-01-10');
INSERT INTO ObjKonta VALUES(3,(SELECT REF(wlasciciel) FROM ObjElita wlasciciel WHERE wlasciciel.nr_czlonka_elity=2),'2017-01-12',NULL);